pipeline {
    agent any

    environment {
        DEPLOY_HOST = credentials('DEPLOY_HOST')  // Store your secrets in Jenkins
        DEPLOY_USER = credentials('DEPLOY_USER')
        SSH_PRIVATE_KEY = credentials('SSH_PRIVATE_KEY')
        SITE_NAME = credentials('SITE_NAME')
        DOCKER_CONTAINER_NAME = 'erpv15'  // Your container name
    }

    stages {
        stage('Deploy') {
            steps {
                script {
                    sshagent(['DEPLOY_CREDENTIALS_ID']) {
                        sh '''
                        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                        chmod 600 ~/.ssh/id_rsa
                        ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
                        
                        ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST <<EOF
                        docker exec ${DOCKER_CONTAINER_NAME} bash -c "
                            su - frappe
                            cd /home/frappe/frappe-env/frappe-bench/apps/wellness
                            git pull
                            bench --site ${SITE_NAME} migrate
                            bench restart
                        "
                        EOF
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up resources if needed"
        }
        failure {
            mail to: 'your-email@example.com',
                 subject: "Build Failed: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
                 body: "Check Jenkins for more details: ${env.BUILD_URL}"
        }
    }
}
