name: Frappe CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-setuptools python3-pip mariadb-client
        pip3 install frappe-bench

    - name: Set up Bench
      run: |
        bench init --skip-redis-config-generation --python python3 frappe-bench
        cd frappe-bench
        bench new-site test-site.local --admin-password admin --mariadb-root-password root
        bench get-app erpnext --branch version-12
        bench --site test-site.local install-app erpnext
        bench --site test-site.local install-app your_app_name

    - name: Run Tests
      run: |
        cd frappe-bench
        bench --site test-site.local run-tests --app your_app_name

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/frappe-bench/apps/wellness/
          git pull origin main
          bench update --requirements
          bench migrate
          sudo systemctl restart frappe
          bench restart
